### ISSUE TITLE
Post to tinyletter

### ISSUE THREAD

**Issue by RichardLitt** [jsvine/tinyapi#1]
Hey! Love this. I might port it over to Javascript at some point. 

Would it be possible to do post to Tinyletter using this API? Or would it be more expedient to set up mail from my terminal so that I can just send a mail directly to the Tinyletter address for my list? 

Which do you think?

**Comment by jsvine** [comment]
Thanks, Richard! In theory, it should be possible to post via this API. In practice, that sort of functionality isn't implemented in `tinyapi` yet. I could look into adding it.

Out of curiosity: What sorts of workflows do you see message-posting enabling?

**Comment by RichardLitt** [comment]
My workflow is that I write a newsletter in the morning, and I use [markdown-to-medium](https://github.com/yoshuawuyts/markdown-to-medium) to post to Medium. It would be great if I could do the same for TinyLetter. 

How did you find the endpoints?

**Comment by jsvine** [comment]
Makes sense! Re. the endpoints: Basically just the `Network` tab on the Chrome developer tools + coffee.

**Comment by jsvine** [comment]
Added in `v0.1.0` (via #2). Let me know if you run into any problems with that.

Example usage here: https://tinyapi.readthedocs.io/en/latest/example-usage.html#creating-and-sending-a-draft

**Comment by RichardLitt** [comment]
This appears to work! Thank you.
